name: sa3ada
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  custom_top_navigator: ^0.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logoapp.png"
  image_path_ios: "assets/images/logoapp.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: TajawalRegular
      fonts:
        - asset: fonts/Tajawal/Tajawal-Regular.ttf
    - family: TajawalBold
      fonts:
        - asset: fonts/Tajawal/Tajawal-Bold.ttf
    - family: TajawalExtraBold
      fonts:
        - asset: fonts/Tajawal/Tajawal-ExtraBold.ttf
    - family: TajawalMedium
      fonts:
        - asset: fonts/Tajawal/Tajawal-Medium.ttf
    - family: TajawalLight
      fonts:
        - asset: fonts/Tajawal/Tajawal-Light.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
